const QUERY_KEY = {
  MBTI: "testResults"
}

const DATE_SLICE_START = 0;
const DATE_SLICE_END = 10;
const TIME_SLICE_START = 11;
const TIME_SLICE_END = 19;

export { QUERY_KEY, DATE_SLICE_START, DATE_SLICE_END, TIME_SLICE_START, TIME_SLICE_END }